---
# tasks file for roles/ubuntu_complete_manager
  - name: Installing Java
    apt:
      name: openjdk-8-jre-headless
      state: latest
      update_cache: yes

  - name: Installing boto,ansible, and openstack
    pip:
      name:
         - boto
         - ansible
         - python-openstackclient
