---
# tasks file for roles/centos_complete_manager
  - name: Installing Java
    yum:
      name: java-11-openjdk-devel
      state: latest
      update_cache: yes

  - name: Installing boto,ansible, and openstack
    pip:
      name:
         - boto
         - ansible
         - python-openstackclient
